### ISSUE TITLE
Organization Name

### ISSUE THREAD

**Issue by Slayther** [for-all-mankind/master#1]
@Slayther:
We need to think of organization name.

---

@Steeevee:
"Since we are going for a civ-like game, I think we should use some kind name that has a historical or mythological vibe."

@Slayther **agrees**.

---

Ideas:
- Anthropocene Studios [1 / 2]
  - (By @Steeevee)
- Chronos Interactive [2 / 2]
  - (By @Steeevee)
  - @Slayther **votes up**

**Comment by Steeevee** [comment]
Since we are going for a civ-like game, I think we should use some kind name that has a historical or mythological vibe.

**Comment by Steeevee** [comment]
Like
Anthropocene Studios
or
Chronos Interactive

**Comment by Slayther** [comment]
Agreed. I don't have any good concrete ideas though.
